"use strict";

export const GET_USERS = "GET_USERS";
export const SET_PAGE = "SET_PAGE";
export const SET_PAGESIZE = "SET_PAGESIZE";
export const REFRESH_USERS = "REFRESH_USERS";
export const CREATE_USER_INFO = "CREATE_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SET_UPDATE_LAYER_VISIBLE = "SET_UPDATE_LAYER_VISIBLE";
export const SET_CREATE_LAYER_VISIBLE = "SET_CREATE_LAYER_VISIBLE";
export const SET_ASSIGN_ROLES_VISIBLE = "SET_ASSIGN_ROLES_VISIBLE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const ASSIGN_ROLES = "ASSIGN_ROLES";
