"use strict";

export const GET_PERIMS_TREE = "GET_PERIMS_TREE";
export const INIT_ROLES = "INIT_ROLES";
export const REMOVE_ROLE = "REMOVE_ROLE";
export const CREATE_ROLE = "CREATE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const SET_CREATE_LAYER_VISIBLE = "SET_CREATE_LAYER_VISIBLE";
export const SET_UPDATE_LAYER_VISIBLE = "SET_UPDATE_LAYER_VISIBLE";
export const SET_ASSIGN_LAYER_VISIBLE = "SET_ASSIGN_LAYER_VISIBLE";
export const ASSIGN_PERMIS = "ASSIGN_PERMIS";
